---
title: "About"
---

I just graduated from my undergrad in May of 2026 from Saint John's University with a major in Mathematics. During undergrad I played on the Saint John's Men's Volleyball team where I was selected as a Captain my Junior and Senior year. I've had two different internships during undergrad, working as a HRIS Analyst for Delta Airlines and a Data Engineer at Commscope, where I grew my pashion for the field of Data Science and Data Engineering. In my freetime I love to go mountaineering, splitboarding/ski touring, climbing, and working out/running. I'm originally from Minnesota in the United States, and I'm also a EU Blue Card eligible citizen. I'm not 100% sure where I'd like to live after finishing the MDS program at UBC but I hope to move to a place where I can continue my pashion for mountaineering and splitboarding to help me keep a solid worklife balance in my future. As a U.S. citizen with a EU Blue card the easiest places for me to move would obviously be in the U.S. or a EU country but I'm also open to living somewhere in Canada!
